### ISSUE TITLE
IFTTT - Error

### ISSUE THREAD

**Issue by TizianGit** [tbtz/immo-check#1]
Hello, 

Thank you for this tool. This can potentially help me a lot!! :-) 
Quick question. I´m trying to set up the IFTTT App, but I´m getting error messages. 
Do you have a suggestion for me?

![image](https://user-images.githubusercontent.com/40239084/193791759-2fc5819d-a0c7-41cf-936a-0b9f21a65012.png)

**Comment by tbtz** [comment]
Hey @TizianGit, sorry for the late awnser, somehow i wasn't notified about new issues.
What is displayed in the text input boxes, if you click on them?
For me it looks (and works) like this:
<img width="947" alt="Bildschirmfoto 2023-06-21 um 17 09 22" src="https://github.com/tbtz/immo-check/assets/9198250/a9997150-582b-4b7c-af60-cb9818c96033">

And what happens if you click on the "Add ingredient" button. Do you also see the "Value1", "Value2", "Value3" options?
<img width="474" alt="Bildschirmfoto 2023-06-21 um 17 09 52" src="https://github.com/tbtz/immo-check/assets/9198250/de3ce639-152e-4531-a8dd-7f0ca0dea79d">

Please give me an update how this looks for you or if you managed to get it running.

**Comment by choerl** [comment]
Works like a charm for me! Cannot reproduce the issue
